language: cpp
compiler:
- gcc
- clang
os:
- linux
sudo: required
dist: trusty
before_script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON -DRUN_TESTS=ON -DCMAKE_BUILD_TYPE=Debug ..
script: make
